### ISSUE TITLE
http before links

### ISSUE THREAD

**Issue by Kolahzary** [steqir/steqir.github.io#5]
hi,
plz add http:// before links in readme.md file

**Comment by Kolahzary** [comment]
answer here plz

**Comment by Kolahzary** [comment]
I didn't meant header link...
plz edit the two links in the list

**Comment by steqir** [comment]
OK

**Comment by steqir** [comment]
it's oK?

**Comment by Kolahzary** [comment]
yeah nice, now close this issue

**Comment by steqir** [comment]
done
